### ISSUE TITLE
Migrate twitter into a separate plugin

### ISSUE THREAD

**Issue by Ariukasq1** [erxes/erxes#3755]
Twitter migrate almost done. But testing every section. Some section hasn't working.
- [x]  Twitter plugin ui
- [x]  Twitter plugin api
- [x] Twitter integration form working fine
- [x]  Config 
- [x] Conversation testing
- [ ]  Refactoring

Testing requests and refactoring twitter integration.

Using Postman checking all request, some request completed done such as authenticating, registering webhook url, receiving message request.

**Comment by Ariukasq1** [comment]
Sprint 9.1

UI:

[x] -  Adding conversation component on twitter
[x] -  Twitter conversation show to inbox ui


API:

[x] - Register webhook request done.
[x] - Refactoring twitter code on integration-plugin
[x] - Twitter message receiving request done.

Sprint 9.2

UI:

[x] -  Twitter messages show to inbox ui
[x] - Refactoring misunderstood account code 
[x] - Conversation detail 


API:

[x] - Sending conversation create RPC messages to inbox 
[x] - Preparing twitter receiving message on twitter plugin
[x] - Refactoring twitter-plugin-api

Now reply message testing...
