### ISSUE TITLE
Time Clock plugin

### ISSUE THREAD

**Issue by nandinboldn** [erxes/erxes#3756]
### Context

Creating a new Time Clock plugin which supports time tracking, creating and exporting time report for members of an organization

**Sprint 6-2**

- [x] Research on timely.mn
- [x] Time tracking when user clocks in & clocks out
- [x] Displaying time report by date range, or by an user

**Sprint 7**
- [x] User sends request for absence
- [x] User fills in their week schedule and sends it as a request prior to that week
- [x] Admin approves or denies absence requests, and the schedule requests
- [x] Displaying absence and schedule requests filtered by an user, date range

**Sprint 8**
- [x] Add branch, and department 
- [x] Report on lateness for work of an user according to their schedule
- [x]  Creates report dynamically according to given department(s) and branches

**Sprint 9**

- [x] Add,Edit,Remove config for pay period, holidays, absence request types
- [x] Display report on employee side
- [x] Compare user's location to branch location and approve/reject the time clock punch in / out
- [x] Create timeclock data if shift request is approved

**Sprint 10**

- [x] Admin sets different configs for submitting schedules
- [x] Admin sets config for absence request types
- [x] Admin assigns config to users, department/branch
- [x] Admins sets config for pay period
- [x] Filter schedules, timeclocks, absence requests by departments / user Ids / branches and  start / end date

**Sprint 11**

- [x] Research on ivms-4200
- [x] Create MSSQL database, and implement tests on it
- [x] Extract data from MSSQL server, clean it, and import it into plugin (Jur ur)
- [x] Merge new data with existing timeclock data

**Sprint 12**

- [x] Add pagination for listing data
- [x] Improve create schedule - date time picker 
- [x] Admin creates, edits, removes timetable config for checking valid clock in /out, and creating default shift start / end
- [x] Select from schedule configs as submitting schedules 

**Sprint 13**

- [x] Improve query for importing data from MySQL
- [x] Compare schedule configs with mssql data in order to import correct time logs into erxes
- [x] Employee submits shift request and gets their time & schedule added 
- [x] Add Date range for extracting data from MySQL

**Sprint 14**
- [x] Display different types of reports according to company’s criteria (preliminary, final, pivot)
- [x] Export reports to xlsx
- [x] Terminal devices config

**Sprint 15**
- [x] Create new time log section, import all time logs from mssql
- [x] Reform/Improve absence config
- [x] Edit time clocks, pick shift start/end from time logs section

**Sprint 16**

- [x] Create custom report for Bichil Globus
- [x] Create check in / check out options for shift request
- [x] Improve filtering by department / branch / user Ids
- [x] Add toggle button for hiding side bar on report section
- [x] Add schedulChecked field into schedules schema for getting schedules checked by employees
- [x] Create reportCheck schema for getting final reports checked by employees on mobile app based on start Date, end Date of the report

**Sprint 17**

- [x] Include detailed Absence info in reports
- [x] Display total days, hours when creating schedule
- [x] Determine holidays when submitting schedule 

**Sprint 18**
- [x] Add remove button for requests
- [x] Add logs schema on cronjob
- [x] Improve check in/out request

**Comment by nomio19** [comment]
Sprint #8

**Comment by nomio19** [comment]
Sprint #9

**Comment by nomio19** [comment]
Sprint #10
