### ISSUE TITLE
Forum plugin - UI

### ISSUE THREAD

**Issue by nomio19** [erxes/erxes#4128]
- [x] move category to settings
- [x] improve post, page and category ui
- [x] move permission and products to settings and improve ui
- [x] add preview to post, page
- [x] improve quiz ui
- [x] refactor code
- [x] upload thumbnail
- [x] edit date
- [x] add search bar to page post
