### ISSUE TITLE
E-commerce plugin

### ISSUE THREAD

**Issue by ghost** [erxes/erxes#4166]
- [ ] Wishlist

**Comment by KhBaterdene** [comment]
- [ ] wishlist  /product hadgalana/
- [ ] olon address hadgalah
- [ ] suuld uzsen budeegdehuunuud
- [ ] hereglegch newterhees omno backend ruu sagsnii medeelliig hadgalah
- [ ] dahiad sanahaaraa nemnee

**Comment by Bilguun0410** [comment]
- [ ] - product review
