### ISSUE TITLE
Performance improvement

### ISSUE THREAD

**Issue by ghost** [erxes/erxes#4167]

**Comment by dulguun0225** [comment]
# Нэг plugin удсан эсвэл унтарсанаас болж хэд хэдэн plugin-аас хамааралтай query тэр чигээрээ удахгүй болгох. Incremental delivery нэвтрүүлэх

- [x] Gateway дээр `@apollo/gateway` `@apollo/server` ашиглахаа больж `apollo router`-аар солих
- [ ] `apollo router` дээр graphql subscription ажилладаг болгох
- [ ] front-end дээрх `apollo client`-ын хувилбарыг 3 болгож query-дээ `@defer` directive ашиглах боломжтой болгох
